version: '3.9'
services:
  app:
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    ports:
      - "5000:5000"
    links:
      - tododb
    depends_on:
      - tododb
  tododb:
    build:
      context: ./
      dockerfile: ./db/Dockerfile
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: TodoDb
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - tododb
    ports:
      - 5555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@developer-blog.net
      PGADMIN_DEFAULT_PASSWORD: admin123